name: Static Files

on:
  push:
    branches:
      - "master"
      - "main"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: yarn && yarn export

      - name: Push Static Files
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: static
          folder: out
          git-config-name: "Jayant Hegde Kageri"
          git-config-email: "jayantkageri@gmail.com"
